#!/usr/bin/env bash
set -Eeuo pipefail

marker='/***** meeque customizations *****/'

if ! grep --quiet --fixed-strings "${marker}" wp-includes/functions.php
then
    (
        echo
        echo "${marker}"
        echo
        echo '// add supported mime types'
        echo 'function mq_add_mime_types( $types ) {'
        echo '    $types["gpx"] = "text/xml";'
        echo '    return $types;'
        echo '}'
        echo 'add_filter( "mime_types", "mq_add_mime_types" );'
        echo 'add_filter( "upload_mimes", "mq_add_mime_types" );'
        echo
        echo '// prevent overly eager resizing of large image uploads'
        echo 'add_filter( "big_image_size_threshold", "__return_false" );'
    ) \
    >> wp-includes/functions.php
fi

exec "$@"

